name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Test package
        run: npm run ci:test
      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel: true

  finish:
    needs: test
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
